from __future__ import annotations

# Families used for contradiction vetoes.
SCIENCE_SLUGS = {
    "physics",
    "chemistry",
    "biology",
    "astronomy",
    "earth",
    "math",
    "engineering",
    "tech",
    "sciences",
}
MEDICINE_SLUGS = {"medicine"}
FICTION_SLUGS = {"novels", "stories", "theatre", "children"}
RELIGION_SLUGS = {
    "din",
    "quran",
    "tafsir",
    "hadith",
    "aqida",
    "fiqh",
    "usul-fiqh",
    "sira",
    "dawa",
    "akhlaq",
    "tasawwuf",
}

# Tokens too generic to assign a category by themselves.
GENERIC_TOKENS = {
    "علم",
    "علوم",
    "كتاب",
    "كتب",
    "مسائل",
    "مساله",
    "شرح",
    "مختصر",
    "رساله",
    "جامع",
    "جزء",
    "فوائد",
    "مجموع",
    "كلام",
    "معاني",
    "صحيح",
    "حديث",
    "نفس",
    "حال",
    "احوال",
    "طبقات",
    "تاريخ",
    "ادب",
    "أدب",
    "قانون",
    "هندسه",
    "رياض",
    "احياء",
    "رجال",
    "روايه",
    "رواية",
}

# OpenITI / GAL / JK / Shamela tags → category slug.
# Keys are matched after stripping @ _ - and case.
# Do NOT map noisy tags: GAL@literature-arabic, GAL@literature-islamic,
# GAL@nodata, _CULUM, _MISC, _MAKHTUTAT, _SUNNI, _SHICI.
TAG_MAP = {
    "gal@hadith": "hadith",
    "_hadith": "hadith",
    "_ajza": "hadith",
    "_masanid": "hadith",
    "_cilal": "hadith",
    "_sunan": "hadith",
    "_sahih": "hadith",
    "_thiqat": "hadith",
    "_takhrij": "hadith",
    "_dacif": "hadith",
    "_mawduc": "hadith",
    "gal@cilm-rijal": "hadith",
    "gal@fiqh": "fiqh",
    "_fiqh": "fiqh",
    "_masail": "fiqh",
    "_ahkam": "fiqh",
    "_qada": "fiqh",
    "_fatawa": "fiqh",
    "_hanafi": "fiqh",
    "_shafici": "fiqh",
    "_hanbali": "fiqh",
    "_maliki": "fiqh",
    "gal@hanbalis": "fiqh",
    "gal@shafiis": "fiqh",
    "gal@hanafis": "fiqh",
    "gal@malikis": "fiqh",
    "_usul": "usul-fiqh",
    "_qawacid": "usul-fiqh",
    "_usuliyya": "usul-fiqh",
    "gal@quran": "quran",
    "gal@quran-sciences": "quran",
    "gal@quran-recitation": "quran",
    "_quran": "quran",
    "_qiraat": "quran",
    "_tajwid": "quran",
    "_mansukh": "quran",
    "_nasikh": "quran",
    "gal@quran-tafsir": "tafsir",
    "gal@quran-interpretation": "tafsir",
    "_tafsir": "tafsir",
    "gal@dogmatics": "aqida",
    "gal@theology": "aqida",
    "_caqaid": "aqida",
    "_milal": "aqida",
    "_firaq": "aqida",
    "gal@sufism": "tasawwuf",
    "gal@mysticism": "tasawwuf",
    "_tasawwuf": "tasawwuf",
    "_suluk": "tasawwuf",
    "_cirfan": "tasawwuf",
    "_akhlaq": "akhlaq",
    "_raqaiq": "akhlaq",
    "_adhkars": "akhlaq",
    "_adhkar": "akhlaq",
    "_tazkiya": "akhlaq",
    "gal@ethics": "akhlaq",
    "gal@paraenetics": "akhlaq",
    "gal@homiletics": "akhlaq",
    "gal@piety": "akhlaq",
    "gal@history-muhammad": "sira",
    "gal@biography-muhammad": "sira",
    "_sira": "sira",
    "_shamail": "sira",
    "_nabi": "sira",
    "_dacwa": "dawa",
    "gal@grammar": "nahw",
    "_nahw": "nahw",
    "_icrab": "nahw",
    "_sarf": "sarf",
    "gal@lexicography": "lexicon",
    "_macajim": "lexicon",
    "_lugha": "arabic-lang",
    "gal@philology": "arabic-lang",
    "gal@linguistics": "linguistics",
    "_balagha": "balagha",
    "_fasaha": "balagha",
    "_carud": "poetry",
    "_shicr": "poetry",
    "_shicr_jahili": "poetry",
    "_shicr_cabasi": "poetry",
    "_shicr_cabbasi": "poetry",
    "_shicr_umawi": "poetry",
    "_shicr_andalusi": "poetry",
    "gal@poetry": "poetry",
    "_adab": "arabic-adab",
    "gal@adab": "arabic-adab",
    "gal@prose": "arabic-adab",
    "_amthal": "arabic-adab",
    "gal@history": "islamic-history",
    "gal@historiography": "islamic-history",
    "gal@history-world": "islamic-history",
    "gal@history-universal": "islamic-history",
    "gal@history-caliphs": "islamic-history",
    "gal@history-imperial": "islamic-history",
    "gal@history-local": "islamic-history",
    "gal@history-prophets": "islamic-history",
    "_tarikh": "islamic-history",
    "_futuh": "islamic-history",
    "gal@history-arabs": "arab-history",
    "gal@biography": "tarajim",
    "gal@biography-collective": "tarajim",
    "gal@biography-individuals": "tarajim",
    "gal@history-individuals": "tarajim",
    "_tarajim": "tarajim",
    "_tabaqat": "tarajim",
    "_wafayat": "tarajim",
    "_ansab": "tarajim",
    "gal@genealogy": "tarajim",
    "gal@medicine": "medicine",
    "_tibb": "medicine",
    "gal@astronomy": "astronomy",
    "gal@astrology": "astronomy",
    "gal@mathematics": "math",
    "gal@philosophy": "philosophy",
    "_falsafa": "philosophy",
    "_mantiq": "philosophy",
    "gal@geographies": "geography",
    "gal@travelogues": "geography",
    "_buldan": "geography",
    "_jughrafiya": "geography",
    "_rihlat": "geography",
    "gal@politics": "politics",
    "_siyasa": "politics",
    "_qisas": "stories",
}

# Phrase lists: longer / more specific phrases first.
POSITIVE: list[tuple[str, tuple[str, ...], float]] = [
    (
        "quran",
        (
            "علوم القران",
            "غريب القران",
            "فضائل القران",
            "قراءات",
            "تجويد",
            "رسم المصحف",
            "ناسخ ومنسوخ",
            "اسباب النزول",
            "لغات القران",
        ),
        0.9,
    ),
    ("quran", ("مصحف", "القران الكريم", "تنزيل القران"), 0.7),
    ("tafsir", ("تفسير القران", "تاويل مشكل", "معاني القران", "مجاز القران", "احكام القران"), 0.85),
    ("tafsir", ("تفسير",), 0.4),
    (
        "hadith",
        (
            "صحيح البخاري",
            "صحيح مسلم",
            "سنن ابي داود",
            "سنن الترمذي",
            "سنن النسائي",
            "سنن ابن ماجه",
            "موطا",
            "الموطا",
            "مسند",
            "علل الحديث",
            "مصطلح الحديث",
            "علوم الحديث",
            "غريب الحديث",
            "جامع الترمذي",
            "مستدرك",
            "مستخرج",
            "الجرح والتعديل",
            "مشيخه",
            "مشيخة",
            "عوالي",
            "ثلاثيات",
            "اربعون حديث",
            "الاربعين",
            "الجامع الصحيح",
        ),
        0.9,
    ),
    ("hadith", ("حديث النبي", "احاديث", "رواه", "اسناد", "اسانيد", "علل"), 0.7),
    (
        "aqida",
        (
            "عقيده",
            "توحيد",
            "الاسماء والصفات",
            "الاشعري",
            "الماتريدي",
            "الملل والنحل",
            "الابانه",
        ),
        0.85,
    ),
    (
        "fiqh",
        (
            "فقه",
            "فتاوى",
            "فتاوي",
            "حنبلي",
            "شافعي",
            "مالكي",
            "حنفي",
            "جعفري",
            "فرائض",
            "مناسك",
            "بيوع",
            "نكاح",
            "طهاره",
        ),
        0.8,
    ),
    ("usul-fiqh", ("اصول الفقه", "مقاصد الشريعه", "القياس", "الاجماع"), 0.85),
    ("sira", ("السيره النبويه", "سيرة النبي", "مغازي", "شمائل", "دلائل النبوه", "خصائص النبي"), 0.9),
    ("sira", ("سيرة",), 0.55),
    ("dawa", ("الدعوه", "موعظه", "مواعظ"), 0.6),
    ("akhlaq", ("اخلاق", "اداب النفس", "رقائق", "زهد", "ورع", "ذنوب"), 0.65),
    ("tasawwuf", ("تصوف", "احياء علوم الدين", "منازل السائرين", "الحكم العطائيه", "سلوك"), 0.85),
    ("nahw", ("النحو", "اعراب", "الفيه ابن مالك", "كتاب سيبويه", "معرب"), 0.85),
    ("sarf", ("الصرف", "التصريف", "التصاريف"), 0.8),
    ("balagha", ("بلاغه", "علم البيان", "البديع", "المعاني والبيان", "دلائل الاعجاز", "اسرار البلاغه"), 0.85),
    ("lexicon", ("معجم", "قاموس", "لسان العرب", "الصحاح", "كتاب العين", "جمهرة", "تهذيب اللغه", "الكنز اللغوي"), 0.8),
    ("linguistics", ("لسانيات", "فيلولوجيا"), 0.8),
    ("language-teaching", ("لغير الناطقين", "تعليم العربيه"), 0.8),
    ("poetry", ("ديوان", "قصيده", "معلقه", "معلقات", "حماسه"), 0.95),
    ("poetry", ("شعر",), 0.55),
    (
        "arabic-adab",
        (
            "كليلة ودمنه",
            "كليلة ودمنة",
            "بخلاء",
            "مقامات",
            "الحيوان للجاحظ",
            "البيان والتبيين",
        ),
        0.85,
    ),
    ("arabic-adab", ("ادب الكاتب", "ادب الدنيا"), 0.7),
    ("criticism", ("نقد الشعر", "نقد ادبي", "عيار الشعر"), 0.75),
    ("theatre", ("مسرحيه", "مسرح"), 0.8),
    ("novels", ("روايه حديثه", "رواية حديثة"), 0.7),
    ("stories", ("قصص", "حكايات", "حكايه"), 0.55),
    (
        "islamic-history",
        (
            "تاريخ الاسلام",
            "تاريخ الرسل",
            "الخلفاء",
            "فتوح",
            "الامم والملوك",
            "البداية والنهايه",
        ),
        0.85,
    ),
    ("arab-history", ("تاريخ العرب", "ايام العرب"), 0.75),
    ("ancient-history", ("تاريخ قديم", "الفرعون", "اشور", "البابلي"), 0.75),
    ("modern-history", ("التاريخ الحديث", "الاستعمار", "النهضه العربيه"), 0.85),
    ("states", ("تاريخ الدوله", "سلطنه", "مملكه"), 0.6),
    ("civilizations", ("حضاره", "الحضارات"), 0.55),
    ("history", ("حوليات", "اخبار الزمان", "تاريخ دمشق", "تاريخ بغداد", "تاريخ الطبري"), 0.7),
    (
        "tarajim",
        (
            "تراجم",
            "وفيات",
            "سير اعلام",
            "طبقات الفقهاء",
            "طبقات الشعراء",
            "طبقات الحفاظ",
            "طبقات الصوفيه",
            "الاعلام",
            "الطبقات الكبرى",
            "جمهرة انساب",
            "انساب",
        ),
        0.8,
    ),
    ("tarajim", ("نسب",), 0.7),
    ("physics", ("فيزياء", "الطبيعيات", "البصريات", "الميكانيكا", "علم الطبيعه"), 0.9),
    ("chemistry", ("كيمياء", "الكيمياء", "الاكسير"), 0.9),
    ("biology", ("بيولوجيا", "علم النبات", "علم الحيوان"), 0.85),
    ("astronomy", ("علم الفلك", "الهيئة", "الزيج", "النجوم الثابته", "المجسطي", "almajisti", "almajest"), 0.85),
    ("astronomy", ("فلك", "انواء"), 0.65),
    ("earth", ("جيولوجيا", "علم الارض"), 0.85),
    ("math", ("رياضيات", "الجبر", "اقليدس", "إقليدس", "ارتماطيقي", "علم العدد", "الحساب الهندي"), 0.9),
    ("engineering", ("الهندسه المعماريه", "حيل بني موسى", "علم الحيل"), 0.8),
    ("tech", ("حاسوب", "برمجه", "ذكاء اصطناعي"), 0.85),
    (
        "medicine",
        (
            "القانون في الطب",
            "في الطب",
            "فردوس الحكمه في الطب",
            "طب النبي",
            "طب الائمه",
            "الاغذيه والادويه",
            "جالينوس",
            "ابقراط",
            "حفظ الصحه",
            "التشريح",
            "العلاج بالاعشاب",
            "فصول ابقراط",
        ),
        0.9,
    ),
    ("medicine", ("الطب", "دواء", "ادويه", "علاج"), 0.55),
    ("philosophy", ("فلسفه", "ارسطو", "افلاطون", "الشفاء لابن سينا", "تهافت", "المنطق"), 0.75),
    ("psychology", ("علم النفس", "سيكولوجيا"), 0.85),
    ("sociology", ("علم الاجتماع",), 0.85),
    ("economics", ("الخراج", "الاموال السلطانيه"), 0.65),
    ("business", ("الاداره", "تجاره"), 0.5),
    ("politics", ("احكام سلطانيه", "السياسه الشرعيه", "نصيحة الملوك"), 0.8),
    ("politics", ("سياسه",), 0.5),
    ("law", ("قانون وضعي", "حقوق الانسان"), 0.7),
    ("geography", ("جغراف", "معجم البلدان", "المسالك والممالك", "صورة الارض", "نزهة المشتاق"), 0.85),
    ("geography", ("بلدان", "مسالك"), 0.6),
    ("education", ("تربيه", "بيداغوجيا"), 0.6),
    ("children", ("للاطفال", "الناشئه", "فتيان"), 0.7),
    ("general", ("موسوعه", "دائره المعارف"), 0.55),
]

RELIGION_MARKERS = (
    "فقه",
    "حديث",
    "تفسير",
    "قران",
    "عقيده",
    "توحيد",
    "سنن",
    "مسند",
    "موطا",
    "فتاوى",
    "شافعي",
    "مالكي",
    "حنبلي",
    "حنفي",
    "تصوف",
    "سيرة النبي",
    "علوم الحديث",
    "غريب الحديث",
    "غريب القران",
    "اصول الفقه",
    "احاديث",
    "الجرح والتعديل",
)

MEDICINE_OVERRIDE = (
    "في الطب",
    "القانون في الطب",
    "طب النبي",
    "طب الائمه",
    "جالينوس",
    "ابقراط",
    "ادويه",
    "اغذيه",
    "العلاج بالاعشاب",
)

PHYSICS_EVIDENCE = ("فيزياء", "الطبيعيات", "البصريات", "الميكانيكا", "علم الطبيعه")
CHEMISTRY_EVIDENCE = ("كيمياء", "الكيمياء", "الاكسير")
MATH_EVIDENCE = ("رياضيات", "الجبر", "المثلثات", "اقليدس", "ارتماطيقي", "علم العدد", "الحساب الهندي")

