TAXONOMY = [
    {
        "slug": "din",
        "name": "الدين",
        "description": "علوم الشريعة والعقيدة والسلوك.",
        "icon": "din",
        "triggers": ["دين", "اسلام", "إسلام", "شريعة"],
        "children": [
            {"slug": "quran", "name": "القرآن وعلومه", "triggers": ["قرآن", "قران", "تجويد", "قراءات", "رسم المصحف", "مصحف", "غريب القرآن"]},
            {"slug": "tafsir", "name": "التفسير", "triggers": ["تفسير", "تاويل", "معاني القرآن"]},
            {"slug": "hadith", "name": "الحديث وعلومه", "triggers": ["حديث", "سنن", "صحيح", "جامع", "مسند", "GAL@hadith", "رجال", "علل", "ثقات"]},
            {"slug": "aqida", "name": "العقيدة", "triggers": ["عقيدة", "توحيد", "اشعري", "ماتريدي", "ملل"]},
            {"slug": "fiqh", "name": "الفقه", "triggers": ["فقه", "حنبلي", "شافعي", "مالكي", "حنفي", "جعفري"]},
            {"slug": "usul-fiqh", "name": "أصول الفقه", "triggers": ["اصول الفقه", "أصول الفقه", "مقاصد"]},
            {"slug": "sira", "name": "السيرة النبوية", "triggers": ["سيرة", "مغازي", "شمائل", "مقتل"]},
            {"slug": "dawa", "name": "الدعوة", "triggers": ["دعوة", "وعظ"]},
            {"slug": "akhlaq", "name": "الأخلاق", "triggers": ["اخلاق", "أخلاق", "آداب", "رقائق"]},
            {"slug": "tasawwuf", "name": "التصوف", "triggers": ["تصوف", "سلوك", "احياء علوم"]},
        ],
    },
    {
        "slug": "lang-adab",
        "name": "اللغة والأدب",
        "description": "علوم العربية والأدب والشعر.",
        "icon": "adab",
        "triggers": ["لغة عربية", "ادب", "أدب"],
        "children": [
            {"slug": "arabic-lang", "name": "اللغة العربية", "triggers": ["لغة عربية"]},
            {"slug": "nahw", "name": "النحو", "triggers": ["نحو", "اعراب", "ألفية"]},
            {"slug": "sarf", "name": "الصرف", "triggers": ["صرف", "تصريف"]},
            {"slug": "balagha", "name": "البلاغة", "triggers": ["بلاغة", "بيان", "بديع", "معاني"]},
            {"slug": "lexicon", "name": "المعاجم", "triggers": ["معجم", "قاموس", "لسان العرب", "الصحاح"]},
            {"slug": "arabic-adab", "name": "الأدب العربي", "triggers": ["ادب عربي", "مقامات", "كليلة"]},
            {"slug": "poetry", "name": "الشعر", "triggers": ["شعر", "ديوان", "قصيد", "_SHICR"]},
            {"slug": "stories", "name": "القصص", "triggers": ["قصة", "قصص", "حكاية"]},
            {"slug": "adab", "name": "الأدب", "triggers": ["ادب", "أدب", "GAL@literature"]},
            {"slug": "linguistics", "name": "اللسانيات", "triggers": ["لسانيات", "فيلولوجيا"]},
            {"slug": "language-teaching", "name": "تعليم اللغة", "triggers": ["تعليم العربية", "لغير الناطقين"]},
            {"slug": "criticism", "name": "النقد الأدبي", "triggers": ["نقد", "بلاغة نقد"]},
            {"slug": "theatre", "name": "المسرح", "triggers": ["مسرح", "مسرحية"]},
            {"slug": "novels", "name": "الروايات", "triggers": ["رواية", "روايه"]},
        ],
    },
    {
        "slug": "history",
        "name": "التاريخ",
        "description": "التاريخ والتراجم والسير.",
        "icon": "history",
        "triggers": ["تاريخ", "حوليات"],
        "children": [
            {"slug": "islamic-history", "name": "التاريخ الإسلامي", "triggers": ["تاريخ الاسلام", "خلفاء"]},
            {"slug": "tarajim", "name": "التراجم والسير", "triggers": ["تراجم", "طبقات", "وفيات", "اعلام"]},
            {"slug": "arab-history", "name": "التاريخ العربي", "triggers": ["تاريخ العرب"]},
            {"slug": "ancient-history", "name": "التاريخ القديم", "triggers": ["قديم", "آشور", "فرعون"]},
            {"slug": "modern-history", "name": "التاريخ الحديث", "triggers": ["التاريخ الحديث", "استعمار", "نهضة"]},
            {"slug": "states", "name": "تاريخ الدول", "triggers": ["دولة", "سلطنة", "مملكة"]},
            {"slug": "civilizations", "name": "الحضارات", "triggers": ["حضارة"]},
        ],
    },
    {
        "slug": "sciences",
        "name": "العلوم",
        "description": "العلوم الطبيعية والرياضية.",
        "icon": "sciences",
        "triggers": ["علوم طبيعية", "علوم تجريبية"],
        "children": [
            {"slug": "physics", "name": "الفيزياء", "triggers": ["فيزياء"]},
            {"slug": "chemistry", "name": "الكيمياء", "triggers": ["كيمياء"]},
            {"slug": "biology", "name": "الأحياء", "triggers": ["احياء", "بيولوجيا"]},
            {"slug": "astronomy", "name": "الفلك", "triggers": ["فلك", "نجوم", "هيئة"]},
            {"slug": "earth", "name": "علوم الأرض", "triggers": ["جيولوجيا", "ارض"]},
            {"slug": "math", "name": "الرياضيات", "triggers": ["رياضيات", "حساب", "جبر", "هندسة رياضية"]},
            {"slug": "engineering", "name": "الهندسة", "triggers": ["هندسة"]},
            {"slug": "tech", "name": "التقنية والحاسب", "triggers": ["حاسوب", "برمجة", "تقنية", "ذكاء"]},
        ],
    },
    {
        "slug": "medicine",
        "name": "الطب والصحة",
        "description": "الطب والصحة والعلاج.",
        "icon": "medicine",
        "triggers": ["في الطب", "صحة", "قانون في الطب", "جالينوس", "ابقراط", "أبقراط", "تشريح", "نبض"],
    },
    {
        "slug": "philosophy",
        "name": "الفلسفة والفكر",
        "description": "الفلسفة والمنطق والفكر.",
        "icon": "philosophy",
        "triggers": ["فلسفة", "منطق", "حكمة", "ارسطو", "أرسطو"],
    },
    {
        "slug": "society",
        "name": "العلوم الاجتماعية",
        "description": "السياسة والجغرافيا والاقتصاد والمجتمع.",
        "icon": "society",
        "triggers": [],
        "children": [
            {"slug": "geography", "name": "الجغرافيا", "triggers": ["جغراف", "بلدان", "مسالك"]},
            {"slug": "politics", "name": "السياسة", "triggers": ["سياسة", "احكام سلطانية"]},
            {"slug": "economics", "name": "الاقتصاد", "triggers": ["اقتصاد", "مال"]},
            {"slug": "psychology", "name": "علم النفس", "triggers": ["نفس", "سيكولوجيا"]},
            {"slug": "sociology", "name": "علم الاجتماع", "triggers": ["اجتماع"]},
            {"slug": "business", "name": "الإدارة والأعمال", "triggers": ["ادارة", "أعمال", "تجارة"]},
            {"slug": "law", "name": "القانون", "triggers": ["قانون", "حقوق"]},
            {"slug": "education", "name": "التربية والتعليم", "triggers": ["تربية", "تعليم", "بيداغوجيا"]},
        ],
    },
    {"slug": "children", "name": "الأطفال", "triggers": ["اطفال", "ناشئة", "فتيان"]},
    {"slug": "general", "name": "الثقافة العامة", "triggers": ["ثقافة", "معارف", "موسوعة"]},
    {
        "slug": "unclassified",
        "name": "غير مصنف",
        "description": "كتب لم يتوفر لها دليل موضوعي كافٍ.",
        "icon": "unclassified",
        "triggers": [],
    },
]
